version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: business_schedule_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: business_schedule
    volumes:
      - mongodb_data:/data/db
    networks:
      - business_schedule_network

volumes:
  mongodb_data:

networks:
  business_schedule_network:
    driver: bridge 