version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: trucking_mongo_dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: business_schedule
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - trucking_network_dev

  # Backend API (Go) - с hot reload
  backend:
    image: golang:1.21-alpine
    container_name: trucking_backend_dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/business_schedule
      - JWT_SECRET=your_very_secret_jwt_key_here_make_it_long_and_secure
      - PORT=8080
    depends_on:
      - mongodb
    networks:
      - trucking_network_dev
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "go mod download && go run main.go"

  # Frontend (React) - с hot reload
  frontend:
    image: node:18-alpine
    container_name: trucking_frontend_dev
    restart: unless-stopped
    ports:
      - "5174:5174"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - trucking_network_dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  mongodb_data_dev:

networks:
  trucking_network_dev:
    driver: bridge 